/** Maps route paths → page titles shown in the Header */
export const PAGE_TITLES = {
  "dashboard":                "Dashboard",
  "dashboard/analytics":      "Analytics",
  "dashboard/forecasting":    "Forecasting",
  "pos":                      "Point of Sale",
  "invoices":                 "Invoices",
  "sales/credit":             "Credit Sales",
  "products":                 "Products",
  "stock":                    "Stock Management",
  "inventory/batch-expiry":   "Batch & Expiry",
  "inventory/bundles":        "Product Bundles",
  "inventory/dead-stock":     "Smart Alerts",
  "purchases/orders":         "Purchase Orders",
  "purchases/grn":            "Goods Receiving",
  "purchases/returns":        "Purchase Returns",
  "purchases/suppliers":      "Suppliers",
  "customers":                "Customers",
  "customers/dues":           "Customer Dues",
  "customers/history":        "Purchase History",
  "customers/loyalty":        "Loyalty Program",
  "recommendations/diagnosis":"Pest Diagnosis",
  "recommendations/dosage":   "Dosage Guide",
  "recommendations/print":    "Print Recommendation",
  "reports":                  "Reports",
  "reports/profit":           "Profit Analysis",
  "reports/margin":           "Margin Analysis",
  "reports/inventory":        "Inventory Report",
  "reports/aging":            "Invoice Aging Report",
  "users":                    "User Management",
  "staff/sales-reps":         "Sales Representatives",
  "staff/audit-logs":         "Audit Logs",
  "shops":                    "My Shop",
  "settings":                 "Settings",
  "profile":                  "Profile",
  "status":                   "Status",
};

/** Maps route paths → [parent, child] breadcrumb pairs */
export const BREADCRUMBS = {
  "dashboard/analytics":      ["Dashboard",    "Analytics"],
  "dashboard/forecasting":    ["Dashboard",    "Forecasting"],
  "sales/credit":             ["Sales",        "Credit Sales"],
  "inventory/batch-expiry":   ["Inventory",    "Batch & Expiry"],
  "inventory/bundles":        ["Inventory",    "Bundles"],
  "inventory/dead-stock":     ["Inventory",    "Smart Alerts"],
  "purchases/orders":         ["Purchases",    "Orders"],
  "purchases/grn":            ["Purchases",    "Goods Receiving"],
  "purchases/returns":        ["Purchases",    "Returns"],
  "purchases/suppliers":      ["Purchases",    "Suppliers"],
  "customers/dues":           ["Customers",    "Dues"],
  "customers/history":        ["Customers",    "History"],
  "customers/loyalty":        ["Customers",    "Loyalty"],
  "recommendations/diagnosis":["Crop Advisory","Diagnosis"],
  "recommendations/dosage":   ["Crop Advisory","Dosage"],
  "recommendations/print":    ["Crop Advisory","Print"],
  "reports/profit":           ["Reports",      "Profit"],
  "reports/margin":           ["Reports",      "Margin"],
  "reports/inventory":        ["Reports",      "Inventory"],
  "staff/sales-reps":         ["Staff",        "Sales Reps"],
  "staff/audit-logs":         ["Staff",        "Audit Logs"],
};
